{% set name = "mdcat" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/swsnr/{{ name }}/archive/refs/tags/{{ name }}-{{ version }}.tar.gz
  sha256: 1789347b35abff00e04f8941c6970a7ab8ae6ad0a0ec7a33fe3ef39021a7b17f

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/swsnr/{{ name }}
  license: MPL-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Show markdown documents on text terminals
  dev_url: https://github.com/swsnr/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
