{% set name = "mdcat" %}
{% set version = "2.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/swsnr/{{ name }}/archive/refs/tags/{{ name }}-{{ version }}.tar.gz
  sha256: 9b7dea0bb527a651ddc17aee08a14176e0a23eb0564c786362e8d6bf43a18c1c

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/swsnr/{{ name }}
  license: MPL-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Show markdown documents on text terminals
  dev_url: https://github.com/swsnr/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
