context:
  version: "2.9.1"

package:
  name: mdcat
  version: ${{ version }}

source:
  url: https://github.com/BIRSAx2/mdcat/archive/mdcat-${{ version }}.tar.gz
  sha256: f0e9b0909a209ffb9f3685b3aa3bb70fb9e71de1770704c4f0daa1c0ed534fb0

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - mdcat --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Show markdown documents on text terminals
  homepage: https://github.com/BIRSAx2/mdcat
  repository: https://github.com/BIRSAx2/mdcat

extra:
  recipe-maintainers:
    - danielnachun
