context:
  version: "2.15.0"

package:
  name: mdcat
  version: ${{ version }}

source:
  url: https://github.com/BIRSAx2/mdcat/archive/mdcat-${{ version }}.tar.gz
  sha256: a70e81e1dfbef05d2a46fa21a0d035ac6881766eaaa425016c27ff27e52357c7

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - mdcat --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Show markdown documents on text terminals
  homepage: https://github.com/BIRSAx2/mdcat
  repository: https://github.com/BIRSAx2/mdcat

extra:
  recipe-maintainers:
    - danielnachun
