context:
  version: "2.18.0"

package:
  name: mdcat
  version: ${{ version }}

source:
  url: https://github.com/BIRSAx2/mdcat/archive/mdcat-${{ version }}.tar.gz
  sha256: a0db6cfb5623396d78420778a077360d3c53fc0252cab28f76af657ddcf0c232

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - mdcat --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Show markdown documents on text terminals
  homepage: https://github.com/BIRSAx2/mdcat
  repository: https://github.com/BIRSAx2/mdcat

extra:
  recipe-maintainers:
    - danielnachun
